let a= undefined;
console.log(a,typeof a);
let b= null;
console.log(b,typeof b);
let c=12;
console.log(c,typeof c);
let d= 4.13;
console.log(d,typeof d);
let e= 100n;
console.log(e,typeof e);
let f="hello";
console.log(f,typeof f);
let g=Symbol();
console.log(g,typeof g);